openapi: 3.0.0
info:
  title: bulk upload
  version: 1.0.0
servers:
  - url: 'http://www.hmislynk.com/hmis-upload-service/rest'
  - url: 'https://www.hmislynk.com/hmis-upload-service/rest'
paths:
  /bulk-upload:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  BulkUploads:
                    pagination:
                      from: 0
                      returned: 1
                      total: 1
                      maximum: 30
                      sort: {}
                    bulkUploads:
                      - dateCreated: 10-07-2017
                        dateUpdated: 10-07-2017
                        fileName: 2017.xml
                        fileSize: 0 bytes
                        year: 2017
                        projectGroupCode: CP0004
                        status: 'STAGING   '
                        id: 336
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errorMessage: internal server error
      description: gets a set of bulk upload
      operationId: GET_bulk-upload
      parameters:
        - name: inactive
          in: query
          description: Filter the list of bulk upload.
          schema:
            type: boolean
    post:
      responses:
        default:
          description: ''
      description: upload a HUD Xml/CSV file for processing.
      operationId: POST_bulk-upload
  '/bulk-upload/{bulk_upload_id}':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  bulkupload:
                    dateUpdated: 11-12-2017
                    fileName: HUD_4_0_Testing.xml
                    fileSize: 62 KB
                    year: 2014
                    projectGroupCode: CP0004
                    status: 'INITIAL '
                    id: 375
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errorMessage: internal server error
      description: retreives bulk upload  details.
      operationId: GET_bulk-upload-bulk_upload_id
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Bulk Upload successfully deleted
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Internal Server Error - retry request'
      description: to delete bulk upload on the basis of uuid
      operationId: DELETE_bulk-upload-bulk_upload_id
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Bulk Upload successfully updated
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Internal Server Error - retry request'
      description: for updating bulk upload status.
      operationId: PUT_bulk-upload-bulk_upload_id
      requestBody:
        content:
          application/json:
            example:
              bulkupload:
                dateCreated: 11-13-2017
                fileName: HUD_4_0_Testing.xml
                fileSize: '63981'
                year: 2014
                projectGroupCode: CP0004
                status: INITIAL
                id: 379
            schema:
              $ref: '#/components/schemas/bulk_upload_id'
        required: true
    parameters:
      - name: bulk_upload_id
        in: path
        required: true
        schema:
          type: string
components:
  schemas:
    bulk_upload:
      required:
        - fileName
        - fileSize
        - projectGroupCode
        - status
        - dateCreated
        - dateUpdated
      type: object
      properties:
        bulkUploadId:
          type: string
        fileName:
          type: string
        fileSize:
          type: string
        projectGroupCode:
          type: string
        status:
          type: string
        dateCreated:
          type: string
        dateUpdated:
          type: string
    bulk_upload_id:
      required:
        - fileName
        - fileSize
        - projectGroupCode
        - status
        - dateCreated
        - dateUpdated
      type: object
      properties:
        bulkUploadId:
          type: string
        fileName:
          type: string
        fileSize:
          type: string
        projectGroupCode:
          type: string
        status:
          type: string
        dateCreated:
          type: string
        dateUpdated:
          type: string
    bulk_upload_ids:
      required:
        - fileName
        - fileSize
        - projectGroupCode
        - status
        - dateCreated
        - dateUpdated
      type: object
      properties:
        bulkUploadId:
          type: string
        fileName:
          type: string
        fileSize:
          type: string
        projectGroupCode:
          type: string
        status:
          type: string
        dateCreated:
          type: string
        dateUpdated:
          type: string
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hmislynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}